In [52]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1DIPxiQpJaEz7RxPPU5jijMt8PxJG2YSd')

# Title Here

An short introduction about PyTorch and about the chosen functions. 

- tensor
- is_nonzero
- numel
- as_tensor
- linspace

Before we begin, let's install and import PyTorch

In [53]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [54]:
# Import torch and other required modules
import torch

## Function 1

In [55]:
# Example 1 - working (change this)
torch.tensor([[42, 212], [1234, 91442]])

tensor([[   42,   212],
        [ 1234, 91442]])

A 2D tensor is created with with 2x2 format, i.e. 2 rows and 2 columns


In [56]:
# Example 2 - working
torch.tensor([[1.042, 21.996452], [123.0000001, 91442.0]])

tensor([[1.0420e+00, 2.1996e+01],
        [1.2300e+02, 9.1442e+04]])

Here is is observed that decimals are converted into scientific format

In [57]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[1, 2,3], [3, 4, 5,6]])

ValueError: ignored

This cell throws an error as n x n, where n is any integer is expexcted but in the 2nd row, 3 elements are present rather than 2 as the other row has 2 elements, hence an error has occured as both rows have different number of elements

Used to create tensors of n x n type 

Let's save our work using Jovian before continuing.

In [58]:
!pip install jovian --upgrade --quiet

In [59]:
import jovian

In [60]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/neelanjan-goswami/01-tensor-operations


'https://jovian.ai/neelanjan-goswami/01-tensor-operations'

## Function 2

In [61]:
# Example 1 - working
torch.is_nonzero(torch.tensor([3]))

True

Returns True if the input is a single element tensor which is not equal to zero after type conversions. i.e. not equal to torch.tensor([0.]) or torch.tensor([0]) or torch.tensor([False]). Throws a RuntimeError if torch.numel() != 1 (even in case of sparse tensors).

In [62]:
# Example 2 - working
torch.is_nonzero(torch.tensor([0]))

False

Since the value is 0, Hence it returns False as its zero

In [63]:
# Example 3 - breaking (to illustrate when it breaks)
torch.is_nonzero(torch.tensor([1, 3, 5]))

RuntimeError: ignored

A sequence of values are not allowed, only single number gives proper output

Used to find non zero tensor values

In [64]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/neelanjan-goswami/01-tensor-operations


'https://jovian.ai/neelanjan-goswami/01-tensor-operations'

## Function 3

In [65]:
# Example 1 - working
a = torch.randn(1, 2, 3, 4, 5)
torch.numel(a)

120

Returns the total number of elements in the input tensor.

In [66]:
# Example 2 - working
a = torch.zeros(4,4)
torch.numel(a)

16

In [67]:
# Example 3 - breaking (to illustrate when it breaks)
a = 0
torch.numel(a)

TypeError: ignored

The function expects a numerical value of zeroes and not null tensor with 0 length


Used to find total inputs to a tensor

In [68]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/neelanjan-goswami/01-tensor-operations


'https://jovian.ai/neelanjan-goswami/01-tensor-operations'

## Function 4

In [69]:
# Example 1 - working
import numpy
a = numpy.array([1, 2, 3])
t = torch.as_tensor(a)
t

tensor([1, 2, 3])

Convert the data into a torch.Tensor. If the data is already a Tensor with the same dtype and device, no copy will be performed, otherwise a new Tensor will be returned with computational graph retained if data Tensor has requires_grad=True. Similarly, if the data is an ndarray of the corresponding dtype and the device is the cpu, no copy will be performed.

In [70]:
# Example 2 - working
a = numpy.array([45.0, 234.2546, 235.3])
t = torch.as_tensor(a)
t

tensor([ 45.0000, 234.2546, 235.3000], dtype=torch.float64)

This can also create tensors with decimal values

In [71]:
# Example 3 - breaking (to illustrate when it breaks)
a = numpy.array([45.0, 234.2546, 'a'])
t = torch.as_tensor(a, dtype=torch.int)
t

TypeError: ignored

It expects numerical values and not lexical value

to convert numpy array to tensor

In [72]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/neelanjan-goswami/01-tensor-operations


'https://jovian.ai/neelanjan-goswami/01-tensor-operations'

## Function 5

In [73]:
# Example 1 - working
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.

In [74]:
# Example 2 - working
torch.linspace(start=-10, end=10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

Now creates a 1D tensor with start and end tags mentioned

In [78]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(start=10, end=5, steps=-1)

RuntimeError: ignored

It expects a positive value of steps by which the range is to be divided

Easily creates a 1D tensor with equal spacing depending on the steps to be taken

In [79]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/neelanjan-goswami/01-tensor-operations


'https://jovian.ai/neelanjan-goswami/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [81]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/neelanjan-goswami/01-tensor-operations


'https://jovian.ai/neelanjan-goswami/01-tensor-operations'